### ISSUE TITLE
[Suggestion] Custom version texts

### ISSUE THREAD

**Issue by RaptaG** [Stereo528/MainMenuChanger#5]
Make so that the user can change the version text to their liking. (Only accessible through modifying the `.json` config file, not the graphic in-game config)

**Comment by Stereo528** [comment]
Sorry for being so late to this, life got busy! I've decided to include it within the GUI config, as I eventually want to build this out to be like every other Custom Main Menu-like mod. Since the title screen redraws whenever it's loaded again (ie going to a different menu and back), you get direct results going to the GUI and back.

Obviously, it's still editable from config but you manually have to go into a menu and back to redraw it (unless I add a refresh button, which might be a pain, I haven't tried yet).

**Comment by Stereo528** [comment]
Done!

**Comment by RaptaG** [comment]
Thanks for everything!
